import turtle
sun=turtle.Turtle()
mercury = turtle.Turtle()
venus = turtle.Turtle()
earth = turtle.Turtle()
mars = turtle.Turtle()
jupiter = turtle.Turtle()
saturn = turtle.Turtle()
sun.shape('circle')
mercury.shape('circle')
venus.shape('circle')
earth.shape('circle')
mars.shape('circle')
jupiter.shape('circle')
saturn.shape('circle')
v=0
mercury.speed(v)
venus.speed(v)
earth.speed(v)
mars.speed(v)
jupiter.speed(v)
saturn.speed(v)
mercury.pu()
venus.pu()
earth.pu()
mars.pu()
jupiter.pu()
saturn.pu()
mercury.setpos(-40,0)
venus.setpos(-80,0)
earth.setpos(-120,0)
mars.setpos(-160,0)
jupiter.setpos(-200,0)
saturn.setpos(-240,0)
mercury.pd()
venus.pd()
earth.pd()
mars.pd()
jupiter.pd()
saturn.pd()
def pl(a,b,c):
    for x in range(-a,a+1):
        y = -(b/a)*(a**2-float(x)**2)**0.5
        c.goto(x,y)
    for x in range(a,-a-1,-1):
        y = (b/a)*(a**2-float(x)**2)**0.5
        c.goto(x,y)
for i in range(1000):
    pl(40,30,mercury)
    pl(80,60,venus)
    pl(120,90,earth)
    pl(160,120,mars)
    pl(200,150,jupiter)
    pl(240,180,saturn)
